/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{html,ts}",],
  theme: {
    extend: {},
  },
  plugins: [],
}

module.exports = {
  content: ["./src/**/*.{html,vue,svelte,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        "title-16px-regular-font-family": "Poppins-Regular, sans-serif",
        "heading-48px-semibold-font-family": "Inter-SemiBold, sans-serif",
        "title-16px-medium-font-family": "Poppins-Medium, sans-serif",
        "title-16px-semibold-font-family": "Poppins-SemiBold, sans-serif",
        "heading-36px-semibold-font-family": "Inter-SemiBold, sans-serif",
        "title-12px-medium-font-family": "Poppins-Medium, sans-serif",
        "heading-32px-bold-font-family": "Inter-Bold, sans-serif",
        "heading-24px-semibold-font-family": "Inter-SemiBold, sans-serif",
        "title-14px-regular-font-family": "Poppins-Regular, sans-serif",
        "title-14px-semibold-font-family": "Poppins-SemiBold, sans-serif",
        "title-12px-regular-font-family": "Poppins-Regular, sans-serif",
        "title-20px-semibold-font-family": "Poppins-SemiBold, sans-serif",
        "title-20px-medium-font-family": "Poppins-Medium, sans-serif",
        "heading-24px-bold-font-family": "Inter-Bold, sans-serif",
      },
      fontSize: {
        "title-16px-regular-font-size": "16px",
        "heading-48px-semibold-font-size": "48px",
        "title-16px-medium-font-size": "16px",
        "title-16px-semibold-font-size": "16px",
        "heading-36px-semibold-font-size": "36px",
        "title-12px-medium-font-size": "12px",
        "heading-32px-bold-font-size": "32px",
        "heading-24px-semibold-font-size": "24px",
        "title-14px-regular-font-size": "14px",
        "title-14px-semibold-font-size": "14px",
        "title-12px-regular-font-size": "12px",
        "title-20px-semibold-font-size": "20px",
        "title-20px-medium-font-size": "20px",
        "heading-24px-bold-font-size": "24px",
      },
      fontWeight: {
        "title-16px-regular-font-weight": "400",
        "heading-48px-semibold-font-weight": "600",
        "title-16px-medium-font-weight": "500",
        "title-16px-semibold-font-weight": "600",
        "heading-36px-semibold-font-weight": "600",
        "title-12px-medium-font-weight": "500",
        "heading-32px-bold-font-weight": "700",
        "heading-24px-semibold-font-weight": "600",
        "title-14px-regular-font-weight": "400",
        "title-14px-semibold-font-weight": "600",
        "title-12px-regular-font-weight": "400",
        "title-20px-semibold-font-weight": "600",
        "title-20px-medium-font-weight": "500",
        "heading-24px-bold-font-weight": "700",
      },
      lineHeight: {
        "title-16px-regular-line-height": "24px",
        "heading-48px-semibold-line-height": "60px",
        "title-16px-medium-line-height": "24px",
        "title-16px-semibold-line-height": "20px",
        "heading-36px-semibold-line-height": "48px",
        "title-12px-medium-line-height": "18px",
        "heading-32px-bold-line-height": "30px",
        "heading-24px-semibold-line-height": "24px",
        "title-14px-regular-line-height": "21px",
        "title-14px-semibold-line-height": "21px",
        "title-12px-regular-line-height": "18px",
        "title-20px-semibold-line-height": "28px",
        "title-20px-medium-line-height": "28px",
        "heading-24px-bold-line-height": "24px",
      },
      letterSpacing: {},
      borderRadius: {},
      colors: {
        bg: "#ffffff",
        text2: "#000000",
        text: "#fafafa",
        "secondary-2": "#db4444",
        primary: "#ffffff",
        button2: "#db4444",
        button: "#000000",
        button1: "#00ff66",
        "hover-button": "#e07575",
        secondary: "#f5f5f5",
        "primary-1": "#2f2e30",
      },
      spacing: {},
      width: {},
      minWidth: {},
      maxWidth: {},
      height: {},
      minHeight: {},
      maxHeight: {},
    },
  },
};
